SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL
FROM EMPLOYEE
WHERE EMP_LNAME LIKE "SMITH%"
ORDER BY EMP_NUM;



SELECT PROJ_NAME, PROJ_VALUE, PROJ_BALANCE,
       EMP_LNAME, EMP_FNAME, EMP_INITIAL,
       JOB_CODE, JOB_DESCRIPTION, JOB_CHG_HOUR
FROM PROJECT 
     JOIN EMPLOYEE USING (EMP_NUM)
     JOIN JOB USING (JOB_CODE)
ORDER BY PROJ_VALUE;



SELECT PROJ_NAME, PROJ_VALUE, PROJ_BALANCE,
       EMP_LNAME, EMP_FNAME, EMP_INITIAL,
       JOB_CODE, JOB_DESCRIPTION, JOB_CHG_HOUR
FROM PROJECT 
     JOIN EMPLOYEE USING (EMP_NUM)
     JOIN JOB USING (JOB_CODE)
ORDER BY EMP_LNAME;




SELECT * FROM ASSIGNMENT ORDER BY PROJ_NUM;

SELECT DISTINCT PROJ_NUM
FROM ASSIGNMENT 
ORDER BY PROJ_NUM;




SELECT ASSIGN_NUM, EMP_NUM, PROJ_NUM, ASSIGN_CHARGE,
       ASSIGN_CHG_HR * ASSIGN_HOURS AS "CALC_ASSIGN_CHARGE"
FROM ASSIGNMENT 
ORDER BY ASSIGN_NUM;




SELECT EMPLOYEE.EMP_NUM, EMPLOYEE.EMP_LNAME,
       round((sum(assignment.assign_hours)),2) as SUMOFASSIGN_HOURS,
       round((sum(assignment.assign_charge)),2) as SUMOFASSIGN_CHARGE
FROM EMPLOYEE
    JOIN ASSIGNMENT ON EMPLOYEE.EMP_NUM=ASSIGNMENT.EMP_NUM
GROUP BY EMP_NUM, EMP_LNAME;





SELECT PROJ_NUM,
       ROUND(SUM(ASSIGN_HOURS),2) AS "SUMOFASSIGN_HOURS"
       ROUND(SUM(ASSIGN_CHARGE),2) AS "SUMOFASSIGN_CHARGE"
FROM ASSIGNMENT 
GROUP BY PROJ_NUM;




SELECT ROUND(SUM(ASSIGN_HOURS),2) AS "SUMOFSUMOFASSIGN_HOURS",
       ROUND(SUM(ASSIGN_CHARGE),2) AS "SUMOFSUMOFASSIGN_CHARGE"
FROM ASSIGNMENT;


